apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mcp-server
  namespace: argocd
spec:
  description: MCP Server project
  sourceRepos:
  - 'https://github.com/token-metrics/mcp.git'
  - 'https://github.com/token-metrics/*'
  destinations:
  - namespace: 'tm-mcp-server'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
    
  # Project roles for RBAC
  roles:
  - name: developer
    description: Developer access to mcp-server applications
    policies:
    - p, proj:mcp-server:developer, applications, get, mcp-server/*, allow
    - p, proj:mcp-server:developer, applications, sync, mcp-server/*, allow
    - p, proj:mcp-server:developer, applications, override, mcp-server/*, allow
    - p, proj:mcp-server:developer, applications, action/*, mcp-server/*, allow
    groups:
    - mcp-developers
  
  - name: admin
    description: Admin access to mcp-server applications
    policies:
    - p, proj:mcp-server:admin, applications, *, mcp-server/*, allow
    - p, proj:mcp-server:admin, repositories, *, *, allow
    groups:
    - mcp-admins
    
  # Sync windows (optional - when sync is allowed)
  syncWindows:
  - kind: allow
    schedule: '* * * * *'  # Always allow for now
    duration: 24h
    applications:
    - '*'