apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-server
  namespace: argocd
spec:
  project: mcp-server
  source:
    repoURL: 'https://github.com/token-metrics/mcp.git'
    targetRevision: HEAD
    path: k8s-manifests/aks
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tm-mcp-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true