name: Build and Push Docker Image
run-name: ${{ github.workflow }} triggered by @${{ github.actor }} for ${{ github.event.head_commit.message }} from ${{ github.ref_name }}
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  docker-build-and-push:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Azure Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tmmcpregistry-hjata4hfarb4fqfa.azurecr.io
          username: ${{ secrets.MCP_REGISTRY_USERNAME }}
          password: ${{ secrets.MCP_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set image tag env
        run: |
          # Generate tag with date and commit SHA
          TAG=$(date +%Y-%m-%d)-${GITHUB_SHA::7}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated tag: $TAG"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: tmmcpregistry-hjata4hfarb4fqfa.azurecr.io/tm-mcp-server:${{ env.TAG }}

      - name: Update deployment.yaml with image tag
        run: |
          BRANCH_NAME=${{ (github.ref_name == 'master' && 'development') }}

          # Configure git for the current repository
          git config --local user.name "seguntokenmetrics"
          git config --local user.email "segun@tokenmetrics.com"

          # Update the tag in the existing deployment.yaml file
          sed -i "s|image: .*|image: tmmcpregistry-hjata4hfarb4fqfa.azurecr.io/tm-mcp-server:${TAG}|" ./k8s-manifests/deployment.yaml
          sed -i "s|image: .*|image: tmmcpregistry-hjata4hfarb4fqfa.azurecr.io/tm-mcp-server:${TAG}|" ./k8s-manifests/aks/deployment.yaml

          git add ./k8s-manifests/deployment.yaml ./k8s-manifests/aks/deployment.yaml
          git commit -m "Update image tag to ${TAG} [skip ci]"

          # Try to push, break if successful
          for i in {1..3}; do
            if git push origin ${{ github.ref_name }}; then
              break
            fi
            sleep 5
          done
        env:
          GITHUB_TOKEN: secrets.GITHUB_TOKEN

