name: CI Pipeline Failure Notification

on:
  workflow_run:
    workflows:
      - "Build and Push Docker Image"
      - "Security Scan"
    types: [completed]
    branches: ["master", "development"]

permissions:
  actions: read
  contents: read

jobs:
  notify-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.name != 'CI Pipeline Failure Notification' }}
    uses: token-metrics/tm-quality-control/.github/workflows/slack-pipeline-alerts.yml@main
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.event.workflow_run.head_branch }}
      workflow_name: ${{ github.event.workflow_run.name }}
      author: ${{ github.event.workflow_run.actor.login }}
      commit_sha: ${{ github.event.workflow_run.head_sha }}
      run_url: ${{ github.event.workflow_run.html_url }}
      jobs_url: ${{ github.event.workflow_run.jobs_url }}
